services:

  client-api:
    build: .
    container_name: client-api
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres-db:5432/clientdb
    depends_on:
      - postgres-db # Wait for the database to upload


  postgres-db:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clientdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: